services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #image: ghcr.io/flemming-pr/weather-station-proxy/main:latest
    ports:
      - "3333:3000"
    env_file:
      - .env
    restart: always
    #platform: linux/amd64
